configuration:
    hub_url: https://hub.browserstack.com/wd/hub
    platform: Windows
    platform_version: 11
    browser: chrome-local
    browser_version: <version>
    username: <bs_username>
    access_key: <bs_access_key>
    build: <bs_build>
    test_name: <any_name>

chrome_flags:
    third_party_cookie_phaseout: --test-third-party-cookie-phaseout
    use-fake-ui-for-media-stream: --use-fake-ui-for-media-stream

chrome_experimental:
    third-party-storage-partitioning: 2
    
chrome_extensions:
    softphone: 'softphone.crx'
    adt_plus: 'adt_plus.crx'